
workflows:
  indbel-release:
    name: IndBel Build Flat
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - '**/app-release.apk'
